# Generated by Django 6.0.6 on 2026-06-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_contact_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
